name: Cargo publish

on:
  push:
    tags:        
      - '*'

jobs:
  publish:
    name: Publish Cargo Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

